"""add_admin_password_reset_columns

Revision ID: 4eb072a66ed1
Revises: a6281480d971
Create Date: 2026-06-04 19:53:41.524778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb072a66ed1'
down_revision: Union[str, Sequence[str], None] = 'a6281480d971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('password_reset_token', sa.Text(), nullable=True))
    op.add_column('admin_users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_admin_users_password_reset_token'), 'admin_users', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_users_password_reset_token'), table_name='admin_users')
    op.drop_column('admin_users', 'password_reset_expires_at')
    op.drop_column('admin_users', 'password_reset_token')
    # ### end Alembic commands ###
