"""add_family_consent_columns

Revision ID: a6281480d971
Revises: 2f99d983611c
Create Date: 2026-06-04 11:57:03.712125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6281480d971'
down_revision: Union[str, Sequence[str], None] = '2f99d983611c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('consent_version', sa.Text(), nullable=True))
    op.add_column('families', sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('families', sa.Column('consent_ip', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'consent_ip')
    op.drop_column('families', 'consent_timestamp')
    op.drop_column('families', 'consent_version')
    # ### end Alembic commands ###
