"""Add notifications table

Revision ID: ec9a30f316c6
Revises: 0002_phase4_payments
Create Date: 2026-06-04 01:41:38.014944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9a30f316c6'
down_revision: Union[str, Sequence[str], None] = '0002_phase4_payments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_admin_users_email'), 'admin_users', type_='unique')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_constraint(op.f('uq_memberships_membership_number'), 'memberships', type_='unique')
    op.create_index(op.f('ix_memberships_membership_number'), 'memberships', ['membership_number'], unique=True)
    op.drop_constraint(op.f('uq_payments_provider_order_id'), 'payments', type_='unique')
    op.drop_constraint(op.f('uq_payments_provider_payment_id'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=True)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.create_unique_constraint(op.f('uq_payments_provider_payment_id'), 'payments', ['provider_payment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_payments_provider_order_id'), 'payments', ['provider_order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_memberships_membership_number'), table_name='memberships')
    op.create_unique_constraint(op.f('uq_memberships_membership_number'), 'memberships', ['membership_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_unique_constraint(op.f('uq_admin_users_email'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
